// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-children.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_children_default = defineTool({
  name: "list_children",
  title: "List children profiles",
  description: "List the signed-in parent's registered children (name, age, interests).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("criancas").select("id, nome, idade, interesses").order("created_at", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { children: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-recent-questions.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_recent_questions_default = defineTool2({
  name: "list_recent_questions",
  title: "List recent questions",
  description: "List the signed-in user's most recent child questions and Kidzz answers.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max rows to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("kidzz_questions_log").select("id, question, answer, age_range, created_at").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { questions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-memories.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.99.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_memories_default = defineTool3({
  name: "list_memories",
  title: "List family memories",
  description: "List saved family memories for the signed-in parent.",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).optional().describe("Max rows to return (default 20)."),
    crianca_id: z2.string().uuid().optional().describe("Optional filter by child id.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, crianca_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser3(ctx).from("memories").select("id, title, content, type, is_special, crianca_id, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (crianca_id) q = q.eq("crianca_id", crianca_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { memories: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/save-memory.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.99.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var save_memory_default = defineTool4({
  name: "save_memory",
  title: "Save family memory",
  description: "Save a new family memory (achievement, moment, note) for a child.",
  inputSchema: {
    crianca_id: z3.string().uuid().describe("Target child id (from list_children)."),
    title: z3.string().trim().min(1).describe("Short memory title."),
    content: z3.string().optional().describe("Optional longer description."),
    type: z3.string().optional().describe("Memory type, e.g. achievement, moment, note."),
    is_special: z3.boolean().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ crianca_id, title, content, type, is_special }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser4(ctx).from("memories").insert({
      user_id: ctx.getUserId(),
      crianca_id,
      title,
      content: content ?? null,
      type: type ?? "moment",
      is_special: is_special ?? false
    }).select("id, title, type, crianca_id, created_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Saved memory ${data.id}` }],
      structuredContent: { memory: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wnowaafqtjoycjhmxsnf";
var mcp_default = defineMcp({
  name: "kidzz-mcp",
  title: "Kidzz MCP",
  version: "0.1.0",
  instructions: "Tools for the Kidzz parenting app. Read the signed-in parent's children, recent questions, and family memories; save new memories. All data is scoped to the authenticated user via Supabase RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_children_default, list_recent_questions_default, list_memories_default, save_memory_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
